from django.contrib.auth import get_user_model
from django.db import transaction
from django.urls import reverse
from rest_framework import serializers

from chat.models import Conversation, Channel, Role, ConversationMember, Topic
from chat.serializers import validate_avatar_file, MessageSerializer


class ChannelCreateSerializer(serializers.ModelSerializer):
    name = serializers.CharField(required=True, allow_blank=False)
    description = serializers.CharField(required=False, allow_blank=True, max_length=500)
    avatar = serializers.FileField(required=False)
    is_private = serializers.BooleanField(default=True)
    public_id = serializers.CharField(required=False, allow_null=True, allow_blank=True)

    class Meta:
        model = Conversation
        fields = ['name', 'description', 'avatar', 'is_private', 'public_id']

    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError("Channel name cannot be empty.")
        return value.strip()

    def validate_avatar(self, value):
        return validate_avatar_file(value)

    def validate(self, data):
        is_private = data.get('is_private', True)
        public_id = data.get('public_id', None)

        if not is_private:
            if not public_id or not public_id.strip():
                raise serializers.ValidationError({
                    'public_id': "Public ID is required for public channels."
                })

            clean_public_id = public_id.strip()

            # ۱. بررسی تکراری نبودن در کانال‌ها (Case-Insensitive)
            if Channel.objects.filter(public_id__iexact=clean_public_id).exists():
                raise serializers.ValidationError({
                    'public_id': "This public ID is already taken by another channel."
                })

            # ۲. بررسی تکراری نبودن در یوزرنیم کاربران (Case-Insensitive)
            User = get_user_model()
            if User.objects.filter(username__iexact=clean_public_id).exists():
                raise serializers.ValidationError({
                    'public_id': "This public ID is already taken by a user."
                })
        else:
            data['public_id'] = None

        return data

    @transaction.atomic
    def create(self, validated_data):
        user = self.context['request'].user
        is_private = validated_data.pop('is_private', True)
        public_id = validated_data.pop('public_id', None)

        # Create the base conversation
        conversation = Conversation.objects.create(
            type=Conversation.Type.CHANNEL,
            name=validated_data.get('name'),
            description=validated_data.get('description', ''),
            avatar=validated_data.get('avatar', None),
            owner=user,
        )

        # Create the channel profile
        Channel.objects.create(
            conversation=conversation,
            is_private=is_private,
            public_id=public_id.strip() if public_id else None,
            # invite_code is auto-generated by default=uuid.uuid4
        )

        # Create "Channel Owner" role
        role = Role.objects.create(
            conversation=conversation,
            name='Channel Owner',
            can_send_messages=True,
            can_send_media=True,
            can_delete_messages=True,
            can_manage_members=True,
            can_manage_roles=True,
            can_view_invite_link=True,
            can_edit_channel_info=True,
            can_delete_channel=True,
            can_create_topic=True,
            can_manage_others_topics=True,
        )

        # Add creator as member with that role
        member = ConversationMember.objects.create(conversation=conversation, user=user)
        member.roles.add(role)

        return conversation


class ChannelDetailSerializer(serializers.ModelSerializer):
    owner_id = serializers.UUIDField(source="owner.id", read_only=True)
    owner_display_name = serializers.CharField(source="owner.display_name", read_only=True)
    avatar_url = serializers.SerializerMethodField()
    invite_link = serializers.SerializerMethodField()

    is_private = serializers.BooleanField(source='channel.is_private', read_only=True)
    public_id = serializers.CharField(source='channel.public_id', read_only=True)

    class Meta:
        model = Conversation
        fields = [
            "id",
            "name",
            "description",
            "avatar",
            "avatar_url",
            "owner_id",
            "owner_display_name",
            "created_at",
            "invite_link",
            "is_private",  # اضافه شد
            "public_id",  # اضافه شد
        ]

    def get_avatar_url(self, obj):
        return obj.avatar_url

    def get_invite_link(self, obj):
        request = self.context.get('request')
        if not request or not hasattr(obj, 'channel'):
            return None

        user = request.user

        has_permission = (obj.owner == user)

        if not has_permission:
            member = obj.members.filter(user=user).prefetch_related('roles').first()
            if member and member.roles.filter(can_view_invite_link=True).exists():
                has_permission = True

        if has_permission:
            invite_code = obj.channel.invite_code
            path = reverse('channel-join', kwargs={'invite_code': invite_code})
            return request.build_absolute_uri(path)

        return None


class ChannelUpdateSerializer(serializers.ModelSerializer):
    avatar = serializers.FileField(required=False, allow_null=True)
    description = serializers.CharField(required=False, allow_blank=True, max_length=500)
    class Meta:
        model = Conversation
        fields = ['name', 'description', 'avatar']

    def validate_name(self, value):
        if not value or not value.strip():
            raise serializers.ValidationError("Channel name cannot be empty.")
        return value.strip()

    def validate_avatar(self, value):
        return validate_avatar_file(value)


class ChannelMemberSerializer(serializers.ModelSerializer):
    user_id = serializers.UUIDField(source='user.id', read_only=True)
    username = serializers.CharField(source='user.username', read_only=True)
    display_name = serializers.CharField(source='user.display_name', read_only=True)
    avatar_url = serializers.CharField(source='user.avatar_url', read_only=True, default=None)
    roles = serializers.SerializerMethodField()
    # Added this line to expose the user's current database online status
    is_online = serializers.BooleanField(source='user.is_online', read_only=True)

    class Meta:
        model = ConversationMember
        fields = ['id', 'user_id', 'username', 'display_name', 'avatar_url', 'roles', 'is_online']

    def get_roles(self, obj):
        role_names = [role.name for role in obj.roles.all()]
        return role_names if role_names else ["Member"]


class ChannelMemberRoleUpdateSerializer(serializers.Serializer):
    role_id = serializers.UUIDField(required=True)


class RoleSerializer(serializers.ModelSerializer):
    class Meta:
        model = Role
        fields = [
            'id', 'name',
            'can_send_messages', 'can_send_media', 'can_delete_messages',
            'can_manage_members', 'can_manage_roles',
            'can_view_invite_link', 'can_edit_channel_info', 'can_delete_channel',
            'can_create_topic', 'can_manage_others_topics',
        ]
        read_only_fields = ['id']


class ChannelMessageSerializer(MessageSerializer):
    topic_id = serializers.SerializerMethodField()
    topic_name = serializers.SerializerMethodField()

    class Meta(MessageSerializer.Meta):
        fields = MessageSerializer.Meta.fields + ['topic_id', 'topic_name']

    def get_topic_id(self, obj):
        return str(obj.topic.id) if obj.topic else None

    def get_topic_name(self, obj):
        return obj.topic.name if obj.topic else None


class TopicCreateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Topic
        fields = ['name']

    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError("Topic name cannot be empty.")
        return value.strip()


class TopicUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = Topic
        fields = ['name']

    def validate_name(self, value):
        if not value.strip():
            raise serializers.ValidationError("Topic name cannot be empty.")
        return value.strip()


class TopicSerializer(serializers.ModelSerializer):
    creator_display_name = serializers.CharField(source='creator.display_name', read_only=True)
    creator_id = serializers.UUIDField(source='creator.id', read_only=True)

    class Meta:
        model = Topic
        fields = ['id', 'name', 'creator_id', 'creator_display_name', 'created_at', 'updated_at']
        read_only_fields = ['id', 'creator_id', 'creator_display_name', 'created_at', 'updated_at']
