# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
# .gitlab-ci.yml
# Pipeline triggers exclusively on the "deployment" branch
# .gitlab-ci.yml
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "deployment"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "deployment"
stages:
  - build
variables:
  HARBOR_HOST: registry.hamdocker.ir
  HARBOR_PROJECT: ayousefnia
  MIRROR_HOST: hub.hamdocker.ir
before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$HARBOR_HOST\":{\"username\":\"$HARBOR_USERNAME\",\"password\":\"$HARBOR_PASSWORD\"}}}" > /kaniko/.docker/config.json
build-frontend:
  stage: build
  image:
    name: gcr.hamdocker.ir/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
        --context="${CI_PROJECT_DIR}/frontend"
        --destination="$HARBOR_HOST/$HARBOR_PROJECT/frontend:$CI_COMMIT_SHA"
        --destination="$HARBOR_HOST/$HARBOR_PROJECT/frontend:latest"
        --registry-mirror=$MIRROR_HOST
        --build-arg REACT_APP_API_URL=$REACT_APP_API_URL
        --cache=true
build-backend:
  stage: build
  image:
    name: gcr.hamdocker.ir/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
        --context="${CI_PROJECT_DIR}/backend"
        --destination="$HARBOR_HOST/$HARBOR_PROJECT/backend:$CI_COMMIT_SHA"
        --destination="$HARBOR_HOST/$HARBOR_PROJECT/backend:latest"
        --registry-mirror=$MIRROR_HOST
        --build-arg PIP_INDEX_URL=$PIP_INDEX_URL
        --cache=true