# Generated by Django 6.0.6 on 2026-07-05 18:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='conversation',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=users.models.avatar_upload_path),
        ),
    ]
