# Generated by Django 5.2.15 on 2026-07-09 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='invite_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
