# Generated by Django 6.0.6 on 2026-07-14 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_invite_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='channel', serialize=False, to='chat.conversation')),
                ('is_private', models.BooleanField(default=True)),
                ('public_id', models.CharField(blank=True, help_text='Unique public identifier, required only for public channels.', max_length=100, null=True, unique=True)),
                ('invite_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Permanent invite code (never changes).', unique=True)),
            ],
        ),
    ]
