# Generated by Django 5.2.15 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_edit_channel_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_invite_link',
            field=models.BooleanField(default=False),
        ),
    ]
