# Generated by Django 6.0.6 on 2026-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_role_can_edit_channel_info_role_can_view_invite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_others_topics',
            field=models.BooleanField(default=False),
        ),
    ]
