# Generated by Django 6.0.6 on 2026-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_topic_channelmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmember',
            name='role',
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='members', to='chat.role'),
        ),
    ]
