# Generated by Django 6.0.6 on 2026-08-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_scheduledmessage_scheduledattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DM', 'Direct Message'), ('REPLY', 'Reply'), ('GROUP_ADDED', 'Added to group'), ('MEMBER_JOINED', 'Member joined')], max_length=20),
        ),
    ]
